domain: yas.100-108-98-79.sslip.io
postgresql:
  replicas: 1
  username: yasadminuser
  password: admin
kafka:
  replicas: 1
zookeeper:
  replicas: 1
elasticsearch:
  replicas: 1
  username: yas
  password: LarUmB3A49NTg9YmgW4=
keycloak:
  bootstrapAdmin:
    username: admin
    password: admin
  backofficeRedirectUrls:
    - http://dev-backoffice.yas.100-108-98-79.sslip.io
    - http://staging-backoffice.yas.100-108-98-79.sslip.io
  storefrontRedirectUrls:
    - http://dev-storefront.yas.100-108-98-79.sslip.io
    - http://staging-storefront.yas.100-108-98-79.sslip.io
  apiRedirectUrls:
    - http://dev-api.yas.100-108-98-79.sslip.io
    - http://staging-api.yas.100-108-98-79.sslip.io
grafana:
  username: admin
  password: admin
redis:
  password: redis
