backend:
  image:
    repository: ghcr.io/23120049/yas-{{service}}
    tag: latest

  nameOverride: {{service}}
  fullnameOverride: {{service}}
  databaseName: {{service}}

  ingress:
    enabled: true
    host: api.yas.100-108-98-79.sslip.io
    path: /{{service}}