hostname: identity.yas.100-108-98-79.sslip.io
ingress:
  enabled: true
  className: nginx
backofficeRedirectUrls:
  - http://dev-backoffice.yas.100-108-98-79.sslip.io
  - http://staging-backoffice.yas.100-108-98-79.sslip.io
storefrontRedirectUrls:
  - http://dev-storefront.yas.100-108-98-79.sslip.io
  - http://staging-storefront.yas.100-108-98-79.sslip.io
apiRedirectUrls:
  - http://dev-api.yas.100-108-98-79.sslip.io
  - http://staging-api.yas.100-108-98-79.sslip.io
postgresql:
  username: yasadminuser
  password: admin

bootstrapAdmin:
  username: admin
  password: admin
