apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: {{ .Values.debeziumConnect.name }}
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: {{ .Values.kafka.name }}-kafka-bootstrap:9092
  image: {{ .Values.debeziumConnect.image }}
  template:
      pod:
        imagePullSecrets:
          - name: ghcr-secret
  resources:
    {{- toYaml .Values.debeziumConnect.resources | nindent 4 }}
  
  groupId: yas-connect-cluster
  configStorageTopic: yas-connect-cluster-configs
  offsetStorageTopic: yas-connect-cluster-offsets
  statusStorageTopic: yas-connect-cluster-status
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: connect-cluster
    offset.storage.topic: kafka_connect_offsets
    config.storage.topic: kafka_connect_configs
    status.storage.topic: kafka_connect_status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    