apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: yas-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: yas-kafka-kafka-bootstrap.infra.svc.cluster.local:9092
  image: {{ .Values.debeziumConnect.image }}

  groupId: yas-connect-cluster
  configStorageTopic: yas-connect-configs
  offsetStorageTopic: yas-connect-offsets
  statusStorageTopic: yas-connect-status
  config:
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  {{- if eq .Values.debeziumConnect.buildImage true }}
  build:
    output:
      type: docker
      image: ghcr.io/23120049/yas-kafka-connect:latest
      pushSecret: ghcr-secret
    plugins:
      - name: debezium-postgres
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.7.4.Final/debezium-connector-postgres-2.7.4.Final-plugin.tar.gz
    resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: "1"

  template:
    pod:
      imagePullSecrets:
        - name: ghcr-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role
                    operator: In
                    values:
                      - kafka

  {{- end }}